FROM node:20-alpine

WORKDIR /app

# Install system dependencies for native modules & OCR
RUN apk add --no-cache vips-dev python3 make g++ openssl vips tesseract-ocr

COPY package.json package-lock.json* ./
RUN npm install

COPY . .
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
